### ISSUE TITLE
Sollumz not working in Blender 5.1

### ISSUE THREAD

**Issue by malik-nomi-67** [Skylumz/Sollumz#1181]
Installed "sollumz"
Successfully installed dependencies. Reloading add-ons...
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 241, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 327, in poll
    if not context.scene.show_mlo_tcm_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_mlo_tcm_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 105, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'
bpy.ops.mesh.primitive_cube_add(size=2, enter_editmode=False, align='WORLD', location=(0, 0, 0), scale=(1, 1, 1))
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 241, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 327, in poll
    if not context.scene.show_mlo_tcm_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_mlo_tcm_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 105, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 241, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 327, in poll
    if not context.scene.show_mlo_tcm_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_mlo_tcm_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 105, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 241, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 327, in poll
    if not context.scene.show_mlo_tcm_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_mlo_tcm_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 105, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 241, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 327, in poll
    if not context.scene.show_mlo_tcm_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_mlo_tcm_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 105, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 241, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 327, in poll
    if not context.scene.show_mlo_tcm_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_mlo_tcm_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 105, in poll
    if not context.scene.show_room_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_room_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 241, in poll
    if not context.scene.show_portal_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_portal_gizmo'
Python: Traceback (most recent call last):
  File "C:\Users\Malik Nomi\AppData\Roaming\Blender Foundation\Blender\5.1\extensions\user_default\sollumz\ytyp\gizmos\mlo.py", line 327, in poll
    if not context.scene.show_mlo_tcm_gizmo:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'show_mlo_tcm_gizmo'

**Comment by alexguirre** [comment]
These errors indicate that something failed during initialization, they are not useful on their own. Right after opening Blender, open the system console and scroll all the way to the beginning and see if you can find a different error.
